server:
  port: 8761

spring:
  application:
    name: culinary-service-registry

culinary:
  configServer:
    username: configserver
    password: 'culinary123'
  serviceRegistry:
    username: serviceregistry
    password: 'culinary123sr'

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      defaultZone: 'http://${culinary.serviceRegistry.username}:${culinary.serviceRegistry.password}@localhost:8761/eureka'